--异步商城订单状态
insert into `tb_mq_consumer` ( `consumer_name`, `consumer_desc`, `queue_name`, `consumer_url`, `url_params`, `request_encoding`, `request_method`, `call_type`, `retry_times`, `create_time`, `last_update_time`, `version`, `status`, `is_handle`)
values('cashmanapp_sync_order_status','同步订单状态','cashmanapp_sync_orderstatus_to_trade_queue','http://TRADE-APP/service/shopping/event/sync-order-status',NULL,'UTF-8','POST','EUREKA','7',now(),now(),'2','7','1');

--新增商城产品表的初始化
insert into `products` (`id`, `name`, `data_valid`, `slogan`, `product_category`, `min_amount`, `max_amount`, `term`, `term_type`, `min_periods`, `max_periods`, `quiet_period`, `interest_rate`, `overdue_rate`, `repay_method`, `updated_time`, `created_user`, `is_prepayment`, `is_renewal`, `start_valid_date`, `created_time`, `end_valid_date`, `is_depository`, `day_payment_max_amount`) values('2','分期商城','1','分期商城描述','3','300000','1000000','30','02','1','3','35','0.0078',NULL,'01','2018-02-24 15:12:52','wang','1','0',NULL,'2018-01-24 13:39:20',NULL,'1','60000000000');
insert into `products_fee_config` (`id`, `data_valid`, `created_user`, `created_time`, `updated_user`, `updated_time`, `fee_name`, `fee_type`, `fee_rate`, `description`, `product_id`, `periods`) values(null,'1','sys','2017-12-18 10:58:41','sys','2018-02-06 16:29:44','利息费','interest_fee','0.0300','利息费','2','1');
insert into `products_fee_config` (`id`, `data_valid`, `created_user`, `created_time`, `updated_user`, `updated_time`, `fee_name`, `fee_type`, `fee_rate`, `description`, `product_id`, `periods`) values(null,'1','sys','2017-12-18 10:58:41','sys','2018-01-29 17:52:56','利息费','interest_fee','0.0300','利息费','2','2');
insert into `products_fee_config` (`id`, `data_valid`, `created_user`, `created_time`, `updated_user`, `updated_time`, `fee_name`, `fee_type`, `fee_rate`, `description`, `product_id`, `periods`) values(null,'1','sys','2017-12-18 10:58:41','sys','2018-02-24 15:12:52','利息费','interest_fee','0.0300','利息费','2','3');
insert into `products_fee_config` (`id`, `data_valid`, `created_user`, `created_time`, `updated_user`, `updated_time`, `fee_name`, `fee_type`, `fee_rate`, `description`, `product_id`, `periods`) values(null,'1','wang','2018-01-24 13:39:20','wang','2018-01-29 17:52:45','利息费','interest_fee','0.0300','利息费','2','4');
insert into `products_fee_config` (`id`, `data_valid`, `created_user`, `created_time`, `updated_user`, `updated_time`, `fee_name`, `fee_type`, `fee_rate`, `description`, `product_id`, `periods`) values(null,'1','sys','2017-12-18 10:58:41','sys','2018-02-06 16:29:44','逾期费','overdue_fee','0.0001','逾期费','2','1');
insert into `products_fee_config` (`id`, `data_valid`, `created_user`, `created_time`, `updated_user`, `updated_time`, `fee_name`, `fee_type`, `fee_rate`, `description`, `product_id`, `periods`) values(null,'1','sys','2017-12-18 10:58:41','sys','2018-01-29 17:52:56','逾期费','overdue_fee','0.0001','逾期费','2','2');
insert into `products_fee_config` (`id`, `data_valid`, `created_user`, `created_time`, `updated_user`, `updated_time`, `fee_name`, `fee_type`, `fee_rate`, `description`, `product_id`, `periods`) values(null,'1','sys','2017-12-18 10:58:41','sys','2018-02-24 15:12:52','逾期费','overdue_fee','0.0001','逾期费','2','3');
insert into `products_fee_config` (`id`, `data_valid`, `created_user`, `created_time`, `updated_user`, `updated_time`, `fee_name`, `fee_type`, `fee_rate`, `description`, `product_id`, `periods`) values(null,'1','wang','2018-01-24 13:39:20','wang','2018-01-29 17:52:45','逾期费','overdue_fee','0.0100','逾期费','2','4');

--分期商城合同初始化
INSERT INTO `contract` (`id`, `contract_name`, `contract_type`, `product_id`, `contract_url`, `description`, `data_valid`, `updated_time`, `created_user`, `created_time`) VALUES(null,'借款协议','LOAN_AGREEMENT','2','http://large-installment.xianjinxia.com/#/loanprotocol',NULL,'1',NULL,'','2018-03-12 00:00:00');
INSERT INTO `contract` (`id`, `contract_name`, `contract_type`, `product_id`, `contract_url`, `description`, `data_valid`, `updated_time`, `created_user`, `created_time`) VALUES(null,'平台服务协议','PLATFORM_SERVICE_AGREEMENT','2','http://large-installment.xianjinxia.com/#/platformservice',NULL,'1',NULL,'','2018-13-12 00:00:00');
