spring:
  application:
    name: cashman-app
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    mode: XHTML
  profiles:
    active: @spring.profile@

server:
  context-path: /
  tomcat:
    accept-count: 1000
    max-threads: 500
    min-spare-threads: 300
    max-connections: 1000

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

eureka:
  client:
    serviceUrl:
        defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

ext:
    swagger:
        title: cashman-app API
        description: cashman-app API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:
